### ISSUE TITLE
AssertionError from MultiError.__init__()

### ISSUE THREAD

**Issue by belm0** [python-trio/trio#1199]
seen in Trio 0.12.1

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/contextlib.py", line 635, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/lib/python3.7/contextlib.py", line 539, in _exit_wrapper
    return await cm_exit(cm, exc_type, exc, tb)
  File "/.../python3.7/site-packages/anyio/_backends/_trio.py", line 123, in __aexit__
    raise TrioExceptionGroup(exc.exceptions) from None
  File "/.../python3.7/site-packages/trio/_core/_multierror.py", line 184, in __init__
    assert len(exceptions) == 1 and exceptions[0] is self
AssertionError
```

**Comment by belm0** [comment]
When `__init__()` is invoked, the `exceptions` class instance member is an empty tuple.  And here is the value of the `exceptions` arg, in all its glory.  (`ConnectionClosed` is from trio_websocket.)
```
 [Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, <MultiError: Cancelled(), Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>, <MultiError: Cancelled(), Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, Cancelled()>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, Cancelled()>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled()>>, Cancelled()>, <MultiError: Cancelled(), Cancelled(), Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, <MultiError: Cancelled(), Cancelled(), Cancelled()>, Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled(), Cancelled()>>>>, <MultiError: Cancelled(), <MultiError: Cancelled(), Cancelled()>, <MultiError: Cancelled(), Cancelled(), <MultiError: Cancelled(), Cancelled()>>>, Cancelled(), ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>, Cancelled()]
```

**Comment by belm0** [comment]
So it's related to anyio exception groups.  The base class has an `exceptions` attribute.

Hmm, I see in anyio head some hack for Trio 0.12 to turn around and delete the attribute.

https://github.com/agronholm/anyio/blob/37c1e21c4edd2a5c35706144f6813139ec57af5f/anyio/exceptions.py#L10-L11

**Comment by belm0** [comment]
I tried anyio HEAD.  Same problem, although now the `exceptions` class instance member is populated rather than an empty tuple:

```
[ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>, <MultiError: ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>, ConnectionClosed<CloseReason<code=1006, name=ABNORMAL_CLOSURE, reason=None>>]
```

So it's to do with multiple inheritance and MultiError?

**Comment by agronholm** [comment]
That change in trio was not particularly welcomed by yours truly, as it completely broke anyio compatibility and I had to do the hack mentioned by @belm0 to work around it. I've never seen guards like that anywhere else. How exactly did you trigger the problem @belm0 ?

**Comment by belm0** [comment]
Are we sure that MultiError worked correctly in the face of subclassing / multiple inheritance even prior to that change?

**Comment by agronholm** [comment]
Well, at least it was fine in anyio as far as I can tell.

**Comment by agronholm** [comment]
@belm0 tell me again, how are you triggering the problem on the latest master version of anyio? The test suite passes just fine.

**Comment by belm0** [comment]
It's a non-trivial app, I can't offer a repro at this point.

I'm sure that the behavior is different between anyio 1.0.0 and head, yet the latter is not sufficient.

From the debugging I did above, I think we can conclude that with subclassing and/or multiple inheritance, there are other paths where __init__() may be called on an existing object, beyond what is assumed in the Trio code.

**Comment by agronholm** [comment]
I guess not. But can you at least find out what exactly is being passed to TrioExceptionGroup's constructor?

**Comment by belm0** [comment]
Sorry, operator error here.  **Indeed, there is not an AssertionError from Trio with anyio HEAD.**

So outstanding is to decide on policy about MultiError inheritance, and whether to make the internals less fragile.

**Comment by Zac-HD** [comment]
Closing this because we've dropped MultiError.
