### ISSUE TITLE
Building lazy-object-proxy with 3.9-dev fails in Travis CI

### ISSUE THREAD

**Issue by pquentin** [python-trio/trio#1415]
The [last good build](https://travis-ci.org/python-trio/trio/jobs/654276161) (2020-02-24) looks like this:

```
Collecting lazy-object-proxy==1.4.3
  Downloading lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
```

The [first bad build](https://travis-ci.org/python-trio/trio/jobs/655564051) (2020-02-27) looks like this:

```
Collecting lazy-object-proxy==1.4.3
  Downloading lazy-object-proxy-1.4.3.tar.gz (34 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/travis/virtualenv/python3.9-dev/bin/python /home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp2g4zkkks
         cwd: /tmp/pip-install-lm7n53m0/lazy-object-proxy
    Complete output (42 lines):
    /home/travis/virtualenv/python3.9-dev/bin/python: No module named pip
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/opt/python/3.9-dev/lib/python3.9/subprocess.py", line 372, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/travis/virtualenv/python3.9-dev/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_gpbjulh', '--quiet', 'setuptools_scm>=3.3.1']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 249, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 61, in <module>
        setup(
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/__init__.py", line 143, in setup
        _install_setup_requires(attrs)
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/__init__.py", line 138, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 781, in resolve
        dist = best[req.key] = env.best_match(
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1066, in best_match
        return self.obtain(req, installer)
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1078, in obtain
        return installer(requirement)
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/home/travis/virtualenv/python3.9-dev/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp_gpbjulh', '--quiet', 'setuptools_scm>=3.3.1']' returned non-zero exit status 1.
```

I guess the interesting line is `/home/travis/virtualenv/python3.9-dev/bin/python: No module named pip`.

This may be a virtualenv issue, which continues to see frequent releases after the rewrite: https://virtualenv.pypa.io/en/latest/changelog.html

And this could be related to the previous failure: https://github.com/python-trio/trio/issues/1402. However that one affected all -dev version, while this issue only affects 3.9-dev.

Also, the Bionic Travis CPython builder https://travis-ci.com/travis-ci/cpython-builder/builds started failing with an OpenSSL 1.1.1 issue two days ago, so it may take some time to fix.

**Comment by pquentin** [comment]
Looks like this was fixed without any changes on our end.
