### ISSUE TITLE
Trio not working on Windows Subsystem for Linux verison 1

### ISSUE THREAD

**Issue by NotoriousRebel** [python-trio/trio#1647]
I installed pyppeteer which uses trio and get this error :( 

attrib() got an unexpected keyword argument 'eq'

Full traceback:

``` % python3.7 screen.py
/usr/local/lib/python3.7/dist-packages/trio/_core/_multierror.py:472: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  category=RuntimeWarning
Traceback (most recent call last):
  File "screen.py", line 2, in <module>
    from pyppeteer import launch
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/__init__.py", line 30, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 25, in <module>
    from pyppeteer.browser import Browser
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/browser.py", line 11, in <module>
    from pyee import EventEmitter
  File "/usr/local/lib/python3.7/dist-packages/pyee/__init__.py", line 59, in <module>
    from pyee._trio import TrioEventEmitter  # noqa
  File "/usr/local/lib/python3.7/dist-packages/pyee/_trio.py", line 4, in <module>
    import trio
  File "/usr/local/lib/python3.7/dist-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/__init__.py", line 19, in <module>
    from ._run import (
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_run.py", line 22, in <module>
    from outcome import Error, Value, capture
  File "/usr/local/lib/python3.7/dist-packages/outcome/__init__.py", line 11, in <module>
    from ._async import Error, Outcome, Value, acapture, capture
  File "/usr/local/lib/python3.7/dist-packages/outcome/_async.py", line 3, in <module>
    from ._sync import Error as ErrorBase
  File "/usr/local/lib/python3.7/dist-packages/outcome/_sync.py", line 28, in <module>
    class Outcome(ABC):
  File "/usr/local/lib/python3.7/dist-packages/outcome/_sync.py", line 43, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "screen.py", line 2, in <module>
    from pyppeteer import launch
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/__init__.py", line 30, in <module>
    from pyppeteer.launcher import connect, launch, executablePath  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/launcher.py", line 25, in <module>
    from pyppeteer.browser import Browser
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/browser.py", line 11, in <module>
    from pyee import EventEmitter
  File "/usr/local/lib/python3.7/dist-packages/pyee/__init__.py", line 59, in <module>
    from pyee._trio import TrioEventEmitter  # noqa
  File "/usr/local/lib/python3.7/dist-packages/pyee/_trio.py", line 4, in <module>
    import trio
  File "/usr/local/lib/python3.7/dist-packages/trio/__init__.py", line 18, in <module>
    from ._core import (
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/__init__.py", line 19, in <module>
    from ._run import (
  File "/usr/local/lib/python3.7/dist-packages/trio/_core/_run.py", line 22, in <module>
    from outcome import Error, Value, capture
  File "/usr/local/lib/python3.7/dist-packages/outcome/__init__.py", line 11, in <module>
    from ._async import Error, Outcome, Value, acapture, capture
  File "/usr/local/lib/python3.7/dist-packages/outcome/_async.py", line 3, in <module>
    from ._sync import Error as ErrorBase
  File "/usr/local/lib/python3.7/dist-packages/outcome/_sync.py", line 28, in <module>
    class Outcome(ABC):
  File "/usr/local/lib/python3.7/dist-packages/outcome/_sync.py", line 43, in Outcome
    _unwrapped = attr.ib(default=False, eq=False, init=False)
TypeError: attrib() got an unexpected keyword argument 'eq'
```
Here is the code snippet I ran with Python 3.7.5
```python
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://example.com')
    await page.screenshot({'path': 'example.png'})
    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

**Comment by njsmith** [comment]
There's a few issues here:

- It sounds like you somehow have a really old version of the `attrs` package installed? I'm not sure how that happened that because your package manager should have taken care of it for you, but that's what those exceptions say. This is causing the program to crash on startup, so you don't even get far enough to try running anything.

- You can't use `asyncio` to run Trio code; you have to use `trio.run` instead

- We do have an issue open for officially supporting WSL1, but progress is stalled because WSL1 is so buggy that there's not a lot we can do: https://github.com/python-trio/trio/issues/893
  Once you reach the point of actually running your code, you might find that you're lucky and you don't hit any of these bugs. But it's a "try it and see" kind of situation – if it doesn't work, then there may not be much we can do to help. I'd suggest switching to WSL2 if you can.

Good luck! I'm going to mark this closed because it doesn't sound like there are any action items for Trio here currently, but feel free to ask more questions, here or in our chat/forum.
