### ISSUE TITLE
TrioInternalError in trio 0.17 with sqlalchemy_aio

### ISSUE THREAD

**Issue by RazerM** [python-trio/trio#1738]
Issue reported by @mozesa in https://github.com/RazerM/sqlalchemy_aio/issues/35

Requirements:
```
pip install sqlalchemy_aio trio==0.17
```
The error does not happen on Trio 0.16.

To reproduce (happens ~50% of the time on my computer), and either very rarely or never with the `trio.sleep(0.1)`:
```python
from pathlib import Path

import trio
from sqlalchemy import Column, Integer, MetaData, Table, create_engine
from sqlalchemy.schema import CreateTable

from sqlalchemy_aio import TRIO_STRATEGY

db_file = Path("test.db")


async def main():
    db_file.unlink(missing_ok=True)
    engine = create_engine(f"sqlite:///{db_file}", strategy=TRIO_STRATEGY)

    metadata = MetaData()
    users = Table("users", metadata, Column("id", Integer, primary_key=True))

    await engine.execute(CreateTable(users))
    # await trio.sleep(0.1)  # seems to work if this is uncommented 


if __name__ == "__main__":
    trio.run(main)
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 2181, in unrolled_run
    runner.task_exited(task, final_outcome)
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 1506, in task_exited
    outcome.unwrap()
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/outcome/_sync.py", line 111, in unwrap
    raise captured_error
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 1599, in init
    run_sync_soon_nursery.cancel_scope.cancel()
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_entry_queue.py", line 57, in kill_everything
    raise exc
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_entry_queue.py", line 53, in run_cb
    sync_fn(*args)
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_threads.py", line 282, in callback
    trio.lowlevel.spawn_system_task(await_in_trio_thread_task, name=afn)
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_generated_run.py", line 146, in spawn_system_task
    return GLOBAL_RUN_CONTEXT.runner.spawn_system_task(async_fn, *args, name=name)
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 1564, in spawn_system_task
    return self.spawn_impl(
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 1424, in spawn_impl
    raise RuntimeError("Nursery is closed to new arrivals")
RuntimeError: Nursery is closed to new arrivals

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/frazer/code/Python/sqlalchemy_aio/issue35.py", line 23, in <module>
    trio.run(main)
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 1919, in run
    timeout = gen.send(next_send)
  File "/Users/frazer/.pyenv/versions/sqlalchemy_aio/lib/python3.8/site-packages/trio/_core/_run.py", line 2226, in unrolled_run
    raise TrioInternalError("internal error in Trio - please file a bug!") from exc
trio.TrioInternalError: internal error in Trio - please file a bug!
```

---

If sqlalchemy_aio is doing something wrong it'll be in [sqlalchemy_aio/trio.py](https://github.com/RazerM/sqlalchemy_aio/blob/a8f9c72fe03d50cc8155681dffa89852978086f7/sqlalchemy_aio/trio.py)

**Comment by RazerM** [comment]
Found the first failing commit with git bisect: https://github.com/python-trio/trio/commit/2947de7eb248e2f33790fb00bc7465490b0e0922

**Comment by njsmith** [comment]
Hmm. Are you calling `trio.from_thread.run` from inside an async generator? It looks like the error is that somehow `trio.from_thread.run` is being called *very* late in trio's shutdown, after the function you passed to `trio.run` has already exited.

We should at least be handling this better... `from_thread.run` never considered the possibility of `spawn_system_task` failing, but that became possible after the async gens shutdown rework.

CC @oremanj

**Comment by RazerM** [comment]
> Are you calling `trio.from_thread.run` from inside an async generator?

No

**Comment by oremanj** [comment]
There's a one-tick interval where the system nursery is closed but we're still taking run_sync_soon callbacks. sqlalchemy_aio appears to use a system task that could reasonably wind up tickling this. I'm working on a fix.
