### ISSUE TITLE
Internal error when exiting an asynccontextmanager

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#1790]
`asynccontextmanager` is no fun. This bug happens, AFAICT, because an asynccontextmanager contains an `async with` which fails and triggers a row of cancellations, which seems to cause internal confusion.

I'm working on building a test case for this but that's far from trivial.

```
pi-e2 ~/moat-bus# ./mb gateway --uri mqtt://10.107.3.2:51883 -p /dev/pill_a
WARNING:distmqtt.client:Client session is not currently connected, ignoring call
Traceback (most recent call last):
  File "../trio/trio/_core/_run.py", line 2190, in unrolled_run
    runner.task_exited(task, final_outcome)
  File "../trio/trio/_core/_run.py", line 1515, in task_exited
    task._parent_nursery._child_finished(task, outcome)
  File "../trio/trio/_core/_run.py", line 909, in _child_finished
    self._check_nursery_closed()
  File "../trio/trio/_core/_run.py", line 903, in _check_nursery_closed
    GLOBAL_RUN_CONTEXT.runner.reschedule(self._parent_task)
  File "../trio/trio/_core/_run.py", line 1403, in reschedule
    assert task._next_send_fn is None
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gw", line 23, in <module>
    trio.run(gateway,"mqtt://10.107.3.2:51883","test/moat/bus",None,"ser_","/dev/ttyUSB0",57600)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 1919, in run
    timeout = gen.send(next_send)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 2226, in unrolled_run
    raise TrioInternalError("internal error in Trio - please file a bug!") from exc
trio.TrioInternalError: internal error in Trio - please file a bug!
```

**Comment by smurfix** [comment]
Possibly related: this code (which triggers the problem but doesn't appear in the above stack trace, natch)
```
    async def run(self):
        try:
            print("N1")
            async with trio.open_nursery() as n:
                print("N2")
                n.start_soon(self.serial2mqtt)
                #n.start_soon(self.mqtt2serial)
            print("N3")    
        except BaseException as exc:
            print("EXC",exc);
            raise

    async def serial2mqtt(self):
        try:
            print("X11")
            async with self.serial as si:
                print("X12")
                async for msg in si:
                    print("X13")
                    await self.mqtt.send_msg(msg)
        except BaseException as exc:
            print("EXC1",exc);
            raise

    async def mqtt2serial(self):
        async with self.mqtt as mi:    
            async for msg in mi:    
                if msg._id.startswith(self.prefix):    
                    continue    
                await self.mqtt.send_msg(msg)    
```

generates this output before the above crash:
```
N1
N2
X11
EXC Cancelled
EXC1 generator didn't yield
Traceback (most recent call last):
…
```
which begs the question why EXC is printed before EXC1 – shouldn't the nursery wait for its children?

**Comment by smurfix** [comment]
Bah. Found it. *Sigh*.

**Comment by smurfix** [comment]
OK, reopening because there's something else going on. Will edit the original.

**Comment by smurfix** [comment]
… as soon as I have a testcase. Sigh. Sleep first.
