### ISSUE TITLE
trio 0.17.0 FAILED trio/_core/tests/test_asyncgen.py::test_fallback_when_no_hook_claims_it fails on alpine linux

### ISSUE THREAD

**Issue by ncopa** [python-trio/trio#1843]
Observed on armv7, s390x and x86_64, so I assume the error happens on all architectures.

This is the alpine build log:
```
>>> py3-trio: Building community/py3-trio 0.17.0-r0 (using abuild 3.7.0_rc1-r2) started Tue, 29 Dec 2020 08:08:31 +0000
>>> py3-trio: Checking sanity of /home/buildozer/aports/community/py3-trio/APKBUILD...
>>> py3-trio: Analyzing dependencies...
>>> py3-trio: Installing for build: build-base python3 py3-sniffio py3-outcome py3-idna py3-sortedcontainers py3-openssl py3-setuptools py3-pytest py3-astor py3-trustme
(1/33) Installing py3-curio (1.4-r0)
(2/33) Installing py3-sniffio (1.2.0-r0)
(3/33) Installing py3-async_generator (1.10-r1)
(4/33) Installing py3-attrs (20.3.0-r0)
(5/33) Installing py3-outcome (1.1.0-r0)
(6/33) Installing py3-idna (2.10-r0)
(7/33) Installing py3-sortedcontainers (2.3.0-r0)
(8/33) Installing py3-cparser (2.20-r0)
(9/33) Installing py3-cffi (1.14.4-r0)
(10/33) Installing py3-asn1crypto (1.4.0-r0)
(11/33) Installing py3-six (1.15.0-r0)
(12/33) Installing py3-cryptography (3.3.1-r0)
(13/33) Installing py3-openssl (20.0.1-r0)
(14/33) Installing py3-ordered-set (4.0.2-r0)
(15/33) Installing py3-appdirs (1.4.4-r1)
(16/33) Installing py3-parsing (2.4.7-r1)
(17/33) Installing py3-packaging (20.8-r0)
(18/33) Installing py3-setuptools (51.0.0-r0)
(19/33) Installing py3-atomicwrites (1.4.0-r0)
(20/33) Installing py3-more-itertools (8.6.0-r0)
(21/33) Installing py3-iniconfig (1.1.1-r0)
(22/33) Installing py3-pluggy (0.13.1-r1)
(23/33) Installing py3-py (1.10.0-r0)
(24/33) Installing py3-wcwidth (0.2.5-r0)
(25/33) Installing py3-toml (0.10.2-r0)
(26/33) Installing py3-pytest (6.2.1-r0)
(27/33) Installing py3-astor (0.8.1-r0)
(28/33) Installing py3-asn1 (0.4.8-r0)
(29/33) Installing py3-asn1-modules (0.2.8-r0)
(30/33) Installing py3-characteristic (14.3.0-r6)
(31/33) Installing py3-service_identity (18.1.0-r3)
(32/33) Installing py3-trustme (0.6.0-r1)
(33/33) Installing .makedepends-py3-trio (20201229.080837)
Executing busybox-1.32.0-r8.trigger
OK: 327 MiB in 135 packages
>>> py3-trio: Cleaning up srcdir
>>> py3-trio: Cleaning up pkgdir
>>> py3-trio: Fetching https://distfiles.alpinelinux.org/distfiles/v3.13/trio-0.17.0.tar.gz
>>> py3-trio: Fetching https://distfiles.alpinelinux.org/distfiles/v3.13/trio-0.17.0.tar.gz
>>> py3-trio: Checking sha512sums...
trio-0.17.0.tar.gz: OK
>>> py3-trio: Unpacking /var/cache/distfiles/v3.13/trio-0.17.0.tar.gz...
running build
running build_py
creating build
creating build/lib
creating build/lib/trio
copying trio/_highlevel_serve_listeners.py -> build/lib/trio
copying trio/to_thread.py -> build/lib/trio
copying trio/socket.py -> build/lib/trio
copying trio/_wait_for_object.py -> build/lib/trio
copying trio/_highlevel_socket.py -> build/lib/trio
copying trio/_highlevel_open_tcp_stream.py -> build/lib/trio
copying trio/_sync.py -> build/lib/trio
copying trio/_threads.py -> build/lib/trio
copying trio/_version.py -> build/lib/trio
copying trio/_highlevel_ssl_helpers.py -> build/lib/trio
copying trio/_abc.py -> build/lib/trio
copying trio/_socket.py -> build/lib/trio
copying trio/_util.py -> build/lib/trio
copying trio/_highlevel_open_tcp_listeners.py -> build/lib/trio
copying trio/abc.py -> build/lib/trio
copying trio/_deprecate.py -> build/lib/trio
copying trio/_highlevel_generic.py -> build/lib/trio
copying trio/_unix_pipes.py -> build/lib/trio
copying trio/from_thread.py -> build/lib/trio
copying trio/lowlevel.py -> build/lib/trio
copying trio/__init__.py -> build/lib/trio
copying trio/_channel.py -> build/lib/trio
copying trio/_highlevel_open_unix_stream.py -> build/lib/trio
copying trio/_file_io.py -> build/lib/trio
copying trio/_path.py -> build/lib/trio
copying trio/_windows_pipes.py -> build/lib/trio
copying trio/_timeouts.py -> build/lib/trio
copying trio/hazmat.py -> build/lib/trio
copying trio/_subprocess.py -> build/lib/trio
copying trio/_signals.py -> build/lib/trio
copying trio/_ssl.py -> build/lib/trio
creating build/lib/trio/tests
copying trio/tests/test_scheduler_determinism.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_serve_listeners.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_open_tcp_stream.py -> build/lib/trio/tests
copying trio/tests/test_path.py -> build/lib/trio/tests
copying trio/tests/test_windows_pipes.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_open_tcp_listeners.py -> build/lib/trio/tests
copying trio/tests/test_timeouts.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_open_unix_stream.py -> build/lib/trio/tests
copying trio/tests/test_threads.py -> build/lib/trio/tests
copying trio/tests/test_socket.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_generic.py -> build/lib/trio/tests
copying trio/tests/test_ssl.py -> build/lib/trio/tests
copying trio/tests/test_channel.py -> build/lib/trio/tests
copying trio/tests/__init__.py -> build/lib/trio/tests
copying trio/tests/test_unix_pipes.py -> build/lib/trio/tests
copying trio/tests/test_signals.py -> build/lib/trio/tests
copying trio/tests/conftest.py -> build/lib/trio/tests
copying trio/tests/test_sync.py -> build/lib/trio/tests
copying trio/tests/test_exports.py -> build/lib/trio/tests
copying trio/tests/test_testing.py -> build/lib/trio/tests
copying trio/tests/test_file_io.py -> build/lib/trio/tests
copying trio/tests/test_abc.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_ssl_helpers.py -> build/lib/trio/tests
copying trio/tests/test_subprocess.py -> build/lib/trio/tests
copying trio/tests/test_deprecate.py -> build/lib/trio/tests
copying trio/tests/test_util.py -> build/lib/trio/tests
copying trio/tests/module_with_deprecations.py -> build/lib/trio/tests
copying trio/tests/test_wait_for_object.py -> build/lib/trio/tests
copying trio/tests/test_highlevel_socket.py -> build/lib/trio/tests
creating build/lib/trio/_subprocess_platform
copying trio/_subprocess_platform/windows.py -> build/lib/trio/_subprocess_platform
copying trio/_subprocess_platform/waitid.py -> build/lib/trio/_subprocess_platform
copying trio/_subprocess_platform/__init__.py -> build/lib/trio/_subprocess_platform
copying trio/_subprocess_platform/kqueue.py -> build/lib/trio/_subprocess_platform
creating build/lib/trio/_core
copying trio/_core/_io_common.py -> build/lib/trio/_core
copying trio/_core/_generated_io_windows.py -> build/lib/trio/_core
copying trio/_core/_generated_run.py -> build/lib/trio/_core
copying trio/_core/_multierror.py -> build/lib/trio/_core
copying trio/_core/_mock_clock.py -> build/lib/trio/_core
copying trio/_core/_entry_queue.py -> build/lib/trio/_core
copying trio/_core/_asyncgens.py -> build/lib/trio/_core
copying trio/_core/_io_epoll.py -> build/lib/trio/_core
copying trio/_core/_generated_io_kqueue.py -> build/lib/trio/_core
copying trio/_core/_unbounded_queue.py -> build/lib/trio/_core
copying trio/_core/_traps.py -> build/lib/trio/_core
copying trio/_core/_wakeup_socketpair.py -> build/lib/trio/_core
copying trio/_core/_exceptions.py -> build/lib/trio/_core
copying trio/_core/__init__.py -> build/lib/trio/_core
copying trio/_core/_local.py -> build/lib/trio/_core
copying trio/_core/_generated_io_epoll.py -> build/lib/trio/_core
copying trio/_core/_thread_cache.py -> build/lib/trio/_core
copying trio/_core/_ki.py -> build/lib/trio/_core
copying trio/_core/_generated_instrumentation.py -> build/lib/trio/_core
copying trio/_core/_run.py -> build/lib/trio/_core
copying trio/_core/_parking_lot.py -> build/lib/trio/_core
copying trio/_core/_instrumentation.py -> build/lib/trio/_core
copying trio/_core/_io_kqueue.py -> build/lib/trio/_core
copying trio/_core/_io_windows.py -> build/lib/trio/_core
copying trio/_core/_windows_cffi.py -> build/lib/trio/_core
creating build/lib/trio/_tools
copying trio/_tools/gen_exports.py -> build/lib/trio/_tools
copying trio/_tools/__init__.py -> build/lib/trio/_tools
creating build/lib/trio/testing
copying trio/testing/_memory_streams.py -> build/lib/trio/testing
copying trio/testing/_checkpoints.py -> build/lib/trio/testing
copying trio/testing/__init__.py -> build/lib/trio/testing
copying trio/testing/_network.py -> build/lib/trio/testing
copying trio/testing/_sequencer.py -> build/lib/trio/testing
copying trio/testing/_trio_test.py -> build/lib/trio/testing
copying trio/testing/_check_streams.py -> build/lib/trio/testing
creating build/lib/trio/tests/tools
copying trio/tests/tools/__init__.py -> build/lib/trio/tests/tools
copying trio/tests/tools/test_gen_exports.py -> build/lib/trio/tests/tools
creating build/lib/trio/_core/tests
copying trio/_core/tests/test_thread_cache.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_asyncgen.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_io.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_run.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_parking_lot.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_instrumentation.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_mock_clock.py -> build/lib/trio/_core/tests
copying trio/_core/tests/tutil.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_multierror.py -> build/lib/trio/_core/tests
copying trio/_core/tests/__init__.py -> build/lib/trio/_core/tests
copying trio/_core/tests/conftest.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_windows.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_tutil.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_ki.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_unbounded_queue.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_guest_mode.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_util.py -> build/lib/trio/_core/tests
copying trio/_core/tests/test_local.py -> build/lib/trio/_core/tests
creating build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/apport_excepthook.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/simple_excepthook_partial.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/simple_excepthook.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/__init__.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/simple_excepthook_IPython.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/ipython_custom_exc.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/custom_excepthook.py -> build/lib/trio/_core/tests/test_multierror_scripts
copying trio/_core/tests/test_multierror_scripts/_common.py -> build/lib/trio/_core/tests/test_multierror_scripts
running egg_info
writing trio.egg-info/PKG-INFO
writing dependency_links to trio.egg-info/dependency_links.txt
writing requirements to trio.egg-info/requires.txt
writing top-level names to trio.egg-info/top_level.txt
reading manifest file 'trio.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pem' under directory 'trio/tests/test_ssl_certs'
no previously-included directories found matching 'docs/build'
writing manifest file 'trio.egg-info/SOURCES.txt'
============================= test session starts ==============================
platform linux -- Python 3.8.7, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /home/buildozer/aports/community/py3-trio/src/trio-0.17.0, configfile: setup.cfg
collected 607 items / 14 deselected / 593 selected

trio/_core/tests/test_asyncgen.py .....F.                                [  1%]
trio/_core/tests/test_guest_mode.py ............                         [  3%]
trio/_core/tests/test_instrumentation.py ........                        [  4%]
trio/_core/tests/test_io.py ............................                 [  9%]
trio/_core/tests/test_ki.py ...........                                  [ 11%]
trio/_core/tests/test_local.py ....                                      [ 11%]
trio/_core/tests/test_mock_clock.py ......                               [ 12%]
trio/_core/tests/test_multierror.py .............ss.ss                   [ 15%]
trio/_core/tests/test_parking_lot.py ....                                [ 16%]
trio/_core/tests/test_run.py ........................................... [ 23%]
...................................................                      [ 32%]
trio/_core/tests/test_thread_cache.py .....                              [ 33%]
trio/_core/tests/test_tutil.py .                                         [ 33%]
trio/_core/tests/test_unbounded_queue.py .....                           [ 34%]
trio/_core/tests/test_windows.py ssssss                                  [ 35%]
trio/tests/test_abc.py ..                                                [ 35%]
trio/tests/test_channel.py ............                                  [ 37%]
trio/tests/test_deprecate.py ...........                                 [ 39%]
trio/tests/test_exports.py ..                                            [ 39%]
trio/tests/test_file_io.py ................                              [ 42%]
trio/tests/test_highlevel_generic.py ..                                  [ 42%]
trio/tests/test_highlevel_open_tcp_listeners.py ..................       [ 45%]
trio/tests/test_highlevel_open_tcp_stream.py ......................      [ 49%]
trio/tests/test_highlevel_open_unix_stream.py .....                      [ 50%]
trio/tests/test_highlevel_serve_listeners.py ....                        [ 51%]
trio/tests/test_highlevel_socket.py .......                              [ 52%]
trio/tests/test_highlevel_ssl_helpers.py ...                             [ 52%]
trio/tests/test_path.py .....................................            [ 59%]
trio/tests/test_scheduler_determinism.py ..                              [ 59%]
trio/tests/test_signals.py ........                                      [ 60%]
trio/tests/test_socket.py .......s.......................                [ 65%]
trio/tests/test_ssl.py ................................................. [ 74%]
................                                                         [ 76%]
trio/tests/test_subprocess.py .................                          [ 79%]
trio/tests/test_sync.py ..................................               [ 85%]
trio/tests/test_testing.py ...................                           [ 88%]
trio/tests/test_threads.py ...............................               [ 93%]
trio/tests/test_timeouts.py ...                                          [ 94%]
trio/tests/test_unix_pipes.py ...........                                [ 96%]
trio/tests/test_util.py .........                                        [ 97%]
trio/tests/test_wait_for_object.py ssss                                  [ 98%]
trio/tests/test_windows_pipes.py ssssss                                  [ 99%]
trio/tests/tools/test_gen_exports.py ...                                 [100%]

=================================== FAILURES ===================================
_____________________ test_fallback_when_no_hook_claims_it _____________________

capsys = <_pytest.capture.CaptureFixture object at 0xf5e65310>

    @pytest.mark.skipif(buggy_pypy_asyncgens, reason="pypy 7.2.0 is buggy")
    async def test_fallback_when_no_hook_claims_it(capsys):
        async def well_behaved():
            yield 42
    
        async def yields_after_yield():
            with pytest.raises(GeneratorExit):
                yield 42
            yield 100
    
        async def awaits_after_yield():
            with pytest.raises(GeneratorExit):
                yield 42
            await _core.cancel_shielded_checkpoint()
    
        await step_outside_async_context(well_behaved())
        gc_collect_harder()
        assert capsys.readouterr().err == ""
    
        await step_outside_async_context(yields_after_yield())
        gc_collect_harder()
>       assert "ignored GeneratorExit" in capsys.readouterr().err
E       AssertionError: assert 'ignored GeneratorExit' in ''
E        +  where '' = CaptureResult(out='', err='').err
E        +    where CaptureResult(out='', err='') = <bound method CaptureFixture.readouterr of <_pytest.capture.CaptureFixture object at 0xf5e65310>>()
E        +      where <bound method CaptureFixture.readouterr of <_pytest.capture.CaptureFixture object at 0xf5e65310>> = <_pytest.capture.CaptureFixture object at 0xf5e65310>.readouterr

trio/_core/tests/test_asyncgen.py:276: AssertionError
=============================== warnings summary ===============================
trio/_core/tests/test_asyncgen.py::test_fallback_when_no_hook_claims_it
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <async_generator object test_fallback_when_no_hook_claims_it.<locals>.yields_after_yield at 0xf61b6610>
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_asyncgens.py", line 101, in finalizer
      closer.send(None)
  RuntimeError: async generator ignored GeneratorExit
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

trio/_core/tests/test_guest_mode.py::test_guest_warns_if_abandoned
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object Runner.init at 0xf5e2fbe8>
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 1582, in init
      self.spawn_impl(
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_generated_run.py", line 53, in current_time
      return GLOBAL_RUN_CONTEXT.runner.current_time()
  AttributeError: 'RunContext' object has no attribute 'runner'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 1591, in init
      self.system_nursery.cancel_scope.cancel()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 802, in __aexit__
      new_exc = await self._nursery._nested_child_finished(exc)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 914, in _nested_child_finished
      self._add_exc(nested_child_exc)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 896, in _add_exc
      self.cancel_scope.cancel()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_ki.py", line 159, in wrapper
      return fn(*args, **kwargs)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 681, in cancel
      self._cancel_status.recalculate()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 350, in recalculate
      current._scope.cancel_called
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 708, in cancel_called
      if not self._cancel_called and current_time() >= self._deadline:
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_generated_run.py", line 55, in current_time
      raise RuntimeError("must be called from async context")
  RuntimeError: must be called from async context
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 1599, in init
      run_sync_soon_nursery.cancel_scope.cancel()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 802, in __aexit__
      new_exc = await self._nursery._nested_child_finished(exc)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 914, in _nested_child_finished
      self._add_exc(nested_child_exc)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 896, in _add_exc
      self.cancel_scope.cancel()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_ki.py", line 159, in wrapper
      return fn(*args, **kwargs)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 681, in cancel
      self._cancel_status.recalculate()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 357, in recalculate
      task._attempt_delivery_of_any_pending_cancel()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 1169, in _attempt_delivery_of_any_pending_cancel
      self._attempt_abort(raise_cancel)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 1151, in _attempt_abort
      success = self._abort_func(raise_cancel)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_io_epoll.py", line 292, in abort
      self._update_registrations(fd)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_io_epoll.py", line 261, in _update_registrations
      self._epoll.modify(fd, wanted_flags | select.EPOLLONESHOT)
  ValueError: I/O operation on closed epoll object
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

trio/_core/tests/test_guest_mode.py::test_guest_mode_asyncgens
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object test_guest_mode_internal_errors.<locals>.crash_in_worker_thread_io at 0xf5faeae8>
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_timeouts.py", line 56, in sleep_until
      await sleep_forever()
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/tests/test_guest_mode.py", line 441, in crash_in_worker_thread_io
      await trio.sleep(1)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_timeouts.py", line 75, in sleep
      await sleep_until(trio.current_time() + seconds)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_timeouts.py", line 56, in sleep_until
      await sleep_forever()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_ki.py", line 159, in wrapper
      return fn(*args, **kwargs)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 549, in __exit__
      raise remaining_error_after_cancel_scope
  RuntimeError: Cancel scope stack corrupted: attempted to exit <trio.CancelScope at 0xf5fb6478, active, cancelled> from unrelated <Task 'trio._core.tests.test_guest_mode.test_guest_mode_asyncgens.<locals>.trio_main' at 0xf6183b08>
  
  This is probably a bug in your code, that has caused Trio's internal state to
  become corrupted. We'll do our best to recover, but from now on there are
  no guarantees.
  
  Typically this is caused by one of the following:
    - yielding within a generator or async generator that's opened a cancel
      scope or nursery (unless the generator is a @contextmanager or
      @asynccontextmanager); see https://github.com/python-trio/trio/issues/638
    - manually calling __enter__ or __exit__ on a trio.CancelScope, or
      __aenter__ or __aexit__ on the object returned by trio.open_nursery();
      doing so correctly is difficult and you should use @[async]contextmanager
      instead, or maybe [Async]ExitStack
    - using [Async]ExitStack to interleave the entries/exits of cancel scopes
      and/or nurseries in a way that couldn't be achieved by some nesting of
      'with' and 'async with' blocks
    - using the low-level coroutine object protocol to execute some parts of
      an async function in a different cancel scope/nursery context than
      other parts
  If you don't believe you're doing any of these things, please file a bug:
  https://github.com/python-trio/trio/issues/new
  
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

trio/_core/tests/test_run.py::test_broken_abort
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object test_broken_abort.<locals>.main at 0xf5b265a8>
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/tests/test_run.py", line 860, in main
      await _core.wait_task_rescheduled(lambda _: None)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_ki.py", line 159, in wrapper
      return fn(*args, **kwargs)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 539, in __exit__
      remaining_error_after_cancel_scope = self._close(exc)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 476, in _close
      scope_task = current_task()
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 2267, in current_task
      raise RuntimeError("must be called from async context") from None
  RuntimeError: must be called from async context
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

trio/_core/tests/test_run.py::test_error_in_run_loop
  /usr/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Nursery.__del__ at 0xf6c9d2b0>
  
  Traceback (most recent call last):
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_run.py", line 1050, in __del__
      assert not self._children
  AssertionError
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

trio/_core/tests/test_thread_cache.py::test_race_between_idle_exit_and_job_assignment
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Trio worker thread 5
  
  Traceback (most recent call last):
    File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/_thread_cache.py", line 71, in _work
      deliver(result)
    File "/home/buildozer/aports/community/py3-trio/src/trio-0.17.0/trio/_core/tests/test_thread_cache.py", line 150, in <lambda>
      tc.start_thread_soon(lambda: None, lambda _: sys.exit())
  SystemExit
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED trio/_core/tests/test_asyncgen.py::test_fallback_when_no_hook_claims_it
==== 1 failed, 571 passed, 21 skipped, 14 deselected, 6 warnings in 36.05s =====
>>> ERROR: py3-trio: check failed
>>> py3-trio: Uninstalling dependencies...
(1/33) Purging .makedepends-py3-trio (20201229.080837)
(2/33) Purging py3-sniffio (1.2.0-r0)
(3/33) Purging py3-curio (1.4-r0)
(4/33) Purging py3-outcome (1.1.0-r0)
(5/33) Purging py3-async_generator (1.10-r1)
(6/33) Purging py3-sortedcontainers (2.3.0-r0)
(7/33) Purging py3-pytest (6.2.1-r0)
(8/33) Purging py3-atomicwrites (1.4.0-r0)
(9/33) Purging py3-more-itertools (8.6.0-r0)
(10/33) Purging py3-iniconfig (1.1.1-r0)
(11/33) Purging py3-pluggy (0.13.1-r1)
(12/33) Purging py3-py (1.10.0-r0)
(13/33) Purging py3-wcwidth (0.2.5-r0)
(14/33) Purging py3-setuptools (51.0.0-r0)
(15/33) Purging py3-ordered-set (4.0.2-r0)
(16/33) Purging py3-appdirs (1.4.4-r1)
(17/33) Purging py3-packaging (20.8-r0)
(18/33) Purging py3-parsing (2.4.7-r1)
(19/33) Purging py3-toml (0.10.2-r0)
(20/33) Purging py3-astor (0.8.1-r0)
(21/33) Purging py3-trustme (0.6.0-r1)
(22/33) Purging py3-openssl (20.0.1-r0)
(23/33) Purging py3-service_identity (18.1.0-r3)
(24/33) Purging py3-asn1-modules (0.2.8-r0)
(25/33) Purging py3-asn1 (0.4.8-r0)
(26/33) Purging py3-attrs (20.3.0-r0)
(27/33) Purging py3-characteristic (14.3.0-r6)
(28/33) Purging py3-cryptography (3.3.1-r0)
(29/33) Purging py3-cffi (1.14.4-r0)
(30/33) Purging py3-cparser (2.20-r0)
(31/33) Purging py3-idna (2.10-r0)
(32/33) Purging py3-asn1crypto (1.4.0-r0)
(33/33) Purging py3-six (1.15.0-r0)
Executing busybox-1.32.0-r8.trigger
OK: 308 MiB in 102 packages
```

**Comment by pquentin** [comment]
Can you try with pytest 6.1.2 instead? We don't support pytest 6.2.1 yet, see #1284

**Comment by ncopa** [comment]
it passed with pytest 6.1.2. I suppose we should skip the specific test for `pytest>=6.2`?

Thank you. This was very helpful.

**Comment by pquentin** [comment]
I see that you fixed the issue for Alpine. As for ourselves, we don't promise to be compatible with all versions of our dependnecies and already have #1824 to track this, so I'll just close this issue. Thank you!

**Comment by graingert** [comment]
@ncopa btw this is now fixed in trio: https://github.com/python-trio/trio/pull/1893
