### ISSUE TITLE
Not Working with s3ql and ubuntu 21.04

### ISSUE THREAD

**Issue by estuaco** [python-trio/trio#1994]
I have issue with trio

/usr/lib/python3/dist-packages/trio/_core/_multierror.py:468: RuntimeWarning: You seem to already have a custom sys.excepthook handler installed. I'll skip installing Trio's custom handler, but this means MultiErrors will not show full tracebacks.
  warnings.warn(
Using 2 upload threads.
Autodetected xxx file descriptors available for cache entries
Detected Swift features for xxx: copy via COPY, Bulk delete 1000 keys at a time, maximum meta value length is 255 bytes
Using cached metadata.
Setting cache size to 13195 MB
Loaded 0 entries from cache
ERROR: Uncaught top-level exception:
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.7.0', 'console_scripts', 'mount.s3ql')())
  File "/usr/lib/s3ql/s3ql/mount.py", line 131, in main
    trio.run(main_async, options, stdout_log_handler)
  File "/usr/lib/python3/dist-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "/usr/lib/s3ql/s3ql/mount.py", line 207, in main_async
    block_cache.init(options.threads)
  File "/usr/lib/s3ql/s3ql/block_cache.py", line 222, in init
    self.trio_token = trio.lowlevel.current_trio_token()
  File "/usr/lib/python3/dist-packages/trio/_deprecate.py", line 125, in __getattr__
    raise AttributeError(name)
AttributeError: lowlevel

**Comment by njsmith** [comment]
It looks like s3ql might need a newer version of trio than what you have
installed... what version of s3ql do you have, and what version of trio do
you have? Did you get them both through your system package manager?

**Comment by estuaco** [comment]
My version of trio is 0.13.0-2, and s3ql is 3.7.0+dfsg-2build1, both from ubuntu 21.04 repository.

**Comment by estuaco** [comment]
@njsmith You are right "pip install -U trio" and trio version 0.18, and work great!!! Thank you!

**Comment by njsmith** [comment]
Sounds like an Ubuntu bug. If you look at s3ql 3.7.0's setup.py, it correctly declares that it needs trio 0.15 or later:

https://github.com/s3ql/s3ql/blob/933fc0a137a573815dd54ed58a82c0a4c7be00ff/setup.py#L146-L147

So Ubuntu shouldn't be shipping s3ql 3.7.0 + trio 0.13 together! I'd file an issue in launchpad.

**Comment by estuaco** [comment]
@njsmith You are right!

**Comment by CafeLungo** [comment]
same error in Ubuntu 21.10. Seems upgrading it manually with the pip command solved it, though.
