### ISSUE TITLE
`traceback_exception_init()` got an unexpected keyword argument 'compact' on Python 3.10

### ISSUE THREAD

**Issue by thedrow** [python-trio/trio#2237]
After running my test suite with pytest 6.2.5 and trio 0.9 instead of 0.8, I got the following error.

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/trio/_core/_multierror.py", line 434, in trio_excepthook
    for chunk in traceback.format_exception(etype, value, tb):
  File "/home/omer/.pyenv/versions/3.10.0/lib/python3.10/traceback.py", line 135, in format_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
TypeError: traceback_exception_init() got an unexpected keyword argument 'compact'

Original exception was:
Traceback (most recent call last):
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/main.py", line 269, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/main.py", line 323, in _main
    config.hook.pytest_runtestloop(session=session)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/main.py", line 348, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/runner.py", line 109, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/runner.py", line 126, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/runner.py", line 217, in call_and_report
    report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/skipping.py", line 272, in pytest_runtest_makereport
    rep = outcome.get_result()
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/runner.py", line 337, in pytest_runtest_makereport
    return TestReport.from_item_and_call(item, call)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/reports.py", line 322, in from_item_and_call
    longrepr = item.repr_failure(excinfo)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/python.py", line 1677, in repr_failure
    return self._repr_failure_py(excinfo, style=style)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/nodes.py", line 398, in _repr_failure_py
    return excinfo.getrepr(
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 648, in getrepr
    return fmt.repr_excinfo(self)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 905, in repr_excinfo
    reprtraceback = self.repr_traceback(excinfo_)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 846, in repr_traceback
    reprentry = self.repr_traceback_entry(entry, einfo)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 798, in repr_traceback_entry
    s = self.get_source(source, line_index, excinfo, short=short)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 736, in get_source
    lines.extend(self.get_exconly(excinfo, indent=indent, markall=True))
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 748, in get_exconly
    exlines = excinfo.exconly(tryshort=True).split("\n")
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 567, in exconly
    lines = format_exception_only(self.type, self.value)
  File "/home/omer/.pyenv/versions/3.10.0/lib/python3.10/traceback.py", line 155, in format_exception_only
    te = TracebackException(type(value), value, None, compact=True)
TypeError: traceback_exception_init() got an unexpected keyword argument 'compact'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/main.py", line 289, in wrap_session
    config.notify_exception(excinfo, config.option)
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1034, in notify_exception
    excrepr = excinfo.getrepr(
  File "/home/omer/.cache/pypoetry/virtualenvs/jumpstarter-ikmlRs0B-py3.10/lib/python3.10/site-packages/_pytest/_code/code.py", line 632, in getrepr
    traceback.format_exception(
  File "/home/omer/.pyenv/versions/3.10.0/lib/python3.10/traceback.py", line 135, in format_exception
    te = TracebackException(type(value), value, tb, limit=limit, compact=True)
TypeError: traceback_exception_init() got an unexpected keyword argument 'compact'
```

This is happening because pytest is trying to format an exception.
It should be possible to reproduce this using https://github.com/celery/jumpstarter/commit/b0f41c6695913e86fdba46319d08b5af7ebc4dda

run `poetry run pytest tests/` to reproduce.

**Comment by pquentin** [comment]
Please update to the latest Trio release, 0.19.0, which is the first to support Python 3.10.

**Comment by thedrow** [comment]
> Please update to the latest Trio release, 0.19.0, which is the first to support Python 3.10.

I am on 0.19, sorry I didn't write the version correctly. Using master fixes the issue.

**Comment by pquentin** [comment]
Thanks for confirming. Since it's fixed in master, I'll keep the issue closed. We plan to release soon :tm:

**Comment by thedrow** [comment]
> Thanks for confirming. Since it's fixed in master, I'll keep the issue closed. We plan to release soon ™️

Please do so ASAP. I also recommend yanking 0.19.

**Comment by pquentin** [comment]
We're definitely not going to rush a release for this, sorry. Also, yanking 0.19 would give you way worse 3.10 support, it would not help in any way

**Comment by thedrow** [comment]
This is a shame since it simply breaks pytest and that's pretty important for knowing your code works :)
I meant yanking 0.19 after releasing 0.19.1. Sorry, I should have been more clear.

**Comment by pquentin** [comment]
Trio 0.20.0 is out with the fix!
