### ISSUE TITLE
file apis don't work well with keyword arguments

### ISSUE THREAD

**Issue by lewoudar** [python-trio/trio#2349]
Hi folks,
For a recent project I needed to read a file in reverse order. I came up with this code

```python
import io
from typing import AsyncIterator
import trio


async def reverse_read_lines(file: str) -> AsyncIterator[bytes]:
    async with await trio.open_file(file, 'rb') as f:
        await f.seek(0, whence=io.SEEK_END)
        pointer = await f.tell()
        buffer = bytearray()

        while pointer >= 0:
            await f.seek(pointer)
            # we read character by character
            pointer -= 1
            char = await f.read(1)

            # if we reach '\n' this means we have read one line and can return it
            if char == b'\n':
                yield buffer[::-1]
                buffer.clear()
            else:
                buffer += char

        # if the buffer is not empty, it is the first line, so we return it
        if buffer:
            yield buffer[::-1]


async def main():
    async for line in reverse_read_lines('foo.txt'):
        print(line)


trio.run(main)
```

To my surprise, I got this error:

```python
/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/bin/python /home/kevin/.config/JetBrains/PyCharm2022.1/scratches/scratch_1.py
Traceback (most recent call last):
  File "/home/kevin/.config/JetBrains/PyCharm2022.1/scratches/scratch_1.py", line 35, in <module>
    trio.run(main)
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/kevin/.config/JetBrains/PyCharm2022.1/scratches/scratch_1.py", line 31, in main
    async for line in reverse_read_lines('foo.txt'):
  File "/home/kevin/.config/JetBrains/PyCharm2022.1/scratches/scratch_1.py", line 8, in reverse_read_lines
    await f.seek(0, whence=io.SEEK_END)
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/trio/_file_io.py", line 79, in wrapper
    return await trio.to_thread.run_sync(func)
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/trio/_threads.py", line 214, in to_thread_run_sync
    return await trio.lowlevel.wait_task_rescheduled(abort)
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/outcome/_impl.py", line 138, in unwrap
    raise captured_error
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/trio/_threads.py", line 160, in do_release_then_return_result
    return result.unwrap()
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/outcome/_impl.py", line 138, in unwrap
    raise captured_error
  File "/home/kevin/.cache/pypoetry/virtualenvs/ws-sc84YdcE-py3.7/lib/python3.7/site-packages/trio/_threads.py", line 174, in worker_fn
    ret = sync_fn(*args)
TypeError: seek() takes no keyword arguments
```

My first use of `seek` raises an error. If I replace trio with [anyio](https://anyio.readthedocs.io/en/stable/) it works well. I believe the issue is related to how trio wraps file operations. The best solution I see now is to implement the whole io api like anyio does [here](https://github.com/agronholm/anyio/blob/48efdec45e70a833cc939c1d2752f24e29d1bf0b/src/anyio/_core/_fileio.py) but.. I found #1960 and it seems like @njsmith does not like this solution.

My environment
- OS: ubuntu 20.04.4 LTS
- Python version 3.7.7
- trio version: 0.20.0

**Comment by Sxderp** [comment]
Well, it's not really a trio issue, but rather a Python API issue. Despite being an optional argument the [`seek` interface](https://docs.python.org/3/library/io.html#io.IOBase.seek) does not take keywords. This is counter to what one would expect in Pure Python, but I think it has to do with C bindings or something.

```
>>> import io
>>> fd = open('sample', 'r')
>>> fd.seek(0, io.SEEK_CUR)
0
>>> fd.seek(0)
0
>>> fd.seek(0, whence=io.SEEK_CUR)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: seek() takes no keyword arguments
```

**Comment by pquentin** [comment]
When anyio will be Python 3.8+, then they'll be able to use [positional-only arguments](https://peps.python.org/pep-0570/), which will avoid the confusion (but break existing users?). Anyway, closing as it's not a Trio issue.
