### ISSUE TITLE
Adapted example code causes 'internal error in Trio'

### ISSUE THREAD

**Issue by danvenn** [python-trio/trio#2398]
I may be doing something dumb here:
```python
import trio, time

def thread_fn(receive_from_trio, send_to_trio):
    while True:
        send_to_trio.send_nowait("Hi")
        time.sleep(1)

async def daemon(receive_from_thread,send_to_thread):
    while True:
        try:
            async for value in receive_from_thread:
                print(value)
        except Exception as ex:
            print(ex)

async def main():
    send_to_thread, receive_from_trio = trio.open_memory_channel(0)
    send_to_trio, receive_from_thread = trio.open_memory_channel(0)

    async with trio.open_nursery() as nursery:

        nursery.start_soon(
            trio.to_thread.run_sync, thread_fn, receive_from_trio, send_to_trio
        )

        nursery.start_soon(daemon, receive_from_thread, send_to_thread)

trio.run(main)
```

but I get this error:
<details>
<summary>Console</summary>

Traceback (most recent call last):
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 2203, in unrolled_run
    runner.task_exited(task, final_outcome)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1524, in task_exited
    task._parent_nursery._child_finished(task, outcome)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 909, in _child_finished
    self._add_exc(outcome.error)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 897, in _add_exc
    self.cancel_scope.cancel()
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_ki.py", line 159, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 679, in cancel
    self._cancel_status.recalculate()
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 345, in recalculate
    task._attempt_delivery_of_any_pending_cancel()
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1175, in _attempt_delivery_of_any_pending_cancel
    self._attempt_abort(raise_cancel)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1157, in _attempt_abort
    success = self._abort_func(raise_cancel)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_channel.py", line 310, in abort_fn
    self._tasks.remove(task)
KeyError: <Task '__main__.daemon' at 0x1ad6764ff60>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Y:\Projects\Mocap\mediapipe\notes\examples\trio_run_sync.py", line 28, in <module>
    trio.run(main)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1937, in run
    timeout = gen.send(next_send)
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 2258, in unrolled_run
    raise TrioInternalError("internal error in Trio - please file a bug!") from exc
trio.TrioInternalError: internal error in Trio - please file a bug!
Exception ignored in: <function Nursery.__del__ at 0x000001AD675241F0>
Traceback (most recent call last):
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1056, in __del__
AssertionError:
Exception ignored in: <coroutine object Runner.init at 0x000001AD677A0890>
Traceback (most recent call last):
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1598, in init
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 800, in __aexit__
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 915, in _nested_child_finished
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 897, in _add_exc
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_ki.py", line 159, in wrapper
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 679, in cancel
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 345, in recalculate
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1175, in _attempt_delivery_of_any_pending_cancel
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1157, in _attempt_abort
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_io_windows.py", line 694, in abort_fn
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_io_windows.py", line 608, in _refresh_afd
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_io_windows.py", line 185, in _check
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_windows_cffi.py", line 323, in raise_winerror
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Nursery.__del__ at 0x000001AD675241F0>
Traceback (most recent call last):
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1056, in __del__
AssertionError:
Exception ignored in: <function Nursery.__del__ at 0x000001AD675241F0>
Traceback (most recent call last):
  File "C:\Users\Dan\anaconda3\envs\mediapipe\lib\site-packages\trio\_core\_run.py", line 1056, in __del__
AssertionError:
</details>
On it's advice I thought I'd better file a bug :)

**Comment by smurfix** [comment]
Not a bug.

Trio queues are not thread safe. You need to use `from_thread` to call them.

**Comment by smurfix** [comment]
NB, next time please also use \`\`\` to quote console output.

**Comment by danvenn** [comment]
Will do, thanks.
