### ISSUE TITLE
RuntimeError: Timeout context manager should be used inside a task

### ISSUE THREAD

**Issue by vadim-a-yegorov** [python-trio/trio#2576]
Code:

```python
import time

from aiohttp_requests import requests
import trio


async def test():
    start = time.time()
    response = await requests.get('http://ifconfig.io/ip')
    speed = int(round(time.time() - start, 3) * 1000)
    external_ip = ''
    if response.status == 200:
        external_ip = (await response.text()).rstrip()

    return speed, external_ip

speed, external_ip = trio.run(test)
print(speed, external_ip)
```

Result:

```
% python ./test_trio.py 
Traceback (most recent call last):
  File "./test_trio.py", line 17, in <module>
    speed, external_ip = trio.run(test)
  File "/Users/dflbv/.pyenv/versions/3.10.4/lib/python3.10/site-packages/trio/_core/_run.py", line 2010, in run
    raise runner.main_task_outcome.error
  File "./test_trio.py", line 9, in test
    response = await requests.get('http://ifconfig.io/ip')
  File "/Users/dflbv/.pyenv/versions/3.10.4/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/Users/dflbv/.pyenv/versions/3.10.4/lib/python3.10/site-packages/aiohttp/helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```

**Comment by vadim-a-yegorov** [comment]
@njsmith

**Comment by A5rocks** [comment]
I don't think that library supports `anyio`/`trio`? I recommend `httpx` instead.

**Comment by vadim-a-yegorov** [comment]
> I don't think that library supports `anyio`/`trio`? I recommend `httpx` instead.

Fixed by rewriting my codebase to use httpx.

**Comment by A5rocks** [comment]
I can't tell if that's sarcastic or not, but I'll close the issue now. It seems you've fixed your issue now and anyways the error is from `aiohttp` and not `trio`!

**Comment by vadim-a-yegorov** [comment]
It’s okay I figured out how to fix the problem
