### ISSUE TITLE
Exception semantics of run_process with strict_exception_groups

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2923]
Currently, with a default of `strict_exception_groups=false`, `run_process` will currently *almost always* return singular exceptions, only giving multiple exceptions (afaik) if it encounters problems with reading from input/output streams.

with #2886 that will change, where any exception encountered when running the user-specified `deliver_cancel`, plus stream errors, will be wrapped. @Zac-HD [initially favored reraising](https://github.com/python-trio/trio/pull/2886#discussion_r1444132356) groups as `TrioInternalError` with the group as a cause - but after [discussion](https://github.com/python-trio/trio/pull/2886#discussion_r1444705230) with @richardsheridan I'm punting it to a separate issue & PR.

Possible solutions include:
* Be open about the fact that there's a nested nursery, and you will get an ExceptionGroup if there's a problem in it. [Status Quo in #2886]
* specify `strict_exception_groups=false` to the nested nursery a la #2845 - but that still leaves the theoretical possibility of getting exceptiongroups in weird cases (unless those are then caught and reraised as a different exceptions), and if we're to deprecate loose exception groups then it seems bad to use it here.
* catch ExceptionGroups from the nursery, and reraise as `TrioInternalError`, unless they're all `Cancelled` so as not to mess with Cancellations.
* Do special handling of exceptions in `deliver_cancel`, marking them and extracting them from the exceptiongroup to be raised.
* If there's only a single exception in the group, extract and raise it.
* Wrap all other exceptions in exceptiongroups.
* ... likely much better solutions I'm not aware of

**Comment by CoolCat467** [comment]
Personally I would put a vote towards wrap everything in an exception group if the function is already raising exception groups and only use `TrioInternalError` if it has been using `TrioInternalError` traditionally (like those stream errors you mentioned)

**Comment by richardsheridan** [comment]
My high level thought on it is that there's nothing really wrong with the exception group except that it's not what was happening before. We could do a newsfragment and update the docs.  If there were an easy and maintainable way to teleport the `deliver_cancel` errors out of the nursery, we should do that. (maybe `Outcome.acapture`?) But, since such errors shouldn't be generated in the normal course of usage, documentation of the wrapping should suffice.

**Comment by jakkdl** [comment]
> My high level thought on it is that there's nothing really wrong with the exception group except that it's not what was happening before. We could do a newsfragment and update the docs. If there were an easy and maintainable way to teleport the `deliver_cancel` errors out of the nursery, we should do that. (maybe `Outcome.acapture`?) But, since such errors shouldn't be generated in the normal course of usage, documentation of the wrapping should suffice.

started looking briefly at teleporting out the error ... but don't we inherently want `run_process` to raise both `Cancelled` and `deliver_cancel` errors (if it was cancelled, which it has to have been if we're running `deliver_cancel`) Or is it fine to swallow the `Cancelled` exception thrown by the nursery and only raise the error from `deliver_cancel`.
Otherwise I don't see a way to not raise an `ExceptionGroup`, other than with loose exception groups, at least in the case where `run_process` is started inside a nursery (e.g. `test_custom_deliver_cancel` or `test_bad_deliver_cancel`.

I whipped together code that passes the current tests .. but I kinda hate it https://github.com/python-trio/trio/compare/master...jakkdl:trio:capture_run_process_deliver_cancel
but maybe there's better ways of managing to achieve it.

**Comment by richardsheridan** [comment]
`acapture` could be outside of `with killer_cscope:` so it can do the `Cancelled` suppression. Although that'll also add yet another nested function, with that suppression logic gone, the error chaining could be a simple `finally: deliver_cancel_outcome.unwrap()`. Then the traceback is of the "during the handling of X, another error occurred" type, which feels right and is guaranteed ungrouped.

**Comment by jakkdl** [comment]
> `acapture` could be outside of `with killer_cscope:` so it can do the `Cancelled` suppression. Although that'll also add yet another nested function, with that suppression logic gone, the error chaining could be a simple `finally: deliver_cancel_outcome.unwrap()` Then the traceback is of the "during the handling of X, another error occurred" type, which feels right and is guaranteed ungrouped.

would you mind adding a commit to the branch, or branching it? I don't fully follow exactly where/how to add the `acapture` and that's probably much easier on both of us than coaching me through it :p

**Comment by richardsheridan** [comment]
This is what I was going for:

https://github.com/python-trio/trio/compare/master...richardsheridan:trio:capture_run_process_deliver_cancel

**Comment by jakkdl** [comment]
Ooh that's much cleaner. Thank you!

I was curious what concrete effect this would have on the output, so I popped out the test into a standalone file (to not get extra tracebacks from pytest stuff).
Status quo (with strict_exception_groups):
```
  + Exception Group Traceback (most recent call last):
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/foo.py", line 23, in <module>
  |     _core.run(do_stuff, strict_exception_groups=True)
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 2275, in run
  |     raise runner.main_task_outcome.error
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/foo.py", line 14, in do_stuff
  |     async with _core.open_nursery() as nursery:
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 971, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 735, in _run_process
    |     async with trio.open_nursery() as nursery:
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 971, in __aexit__
    |     raise combined_error_from_nursery
    | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 761, in killer
      |     await deliver_cancel(proc)
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/foo.py", line 11, in custom_deliver_cancel
      |     raise ValueError("foo")
      | ValueError: foo
      +------------------------------------
```
Reraising the outcome in the finally:
```
  + Exception Group Traceback (most recent call last):
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/foo.py", line 23, in <module>
  |     _core.run(do_stuff, strict_exception_groups=True)
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 2275, in run
  |     raise runner.main_task_outcome.error
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/foo.py", line 14, in do_stuff
  |     async with _core.open_nursery() as nursery:
  |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 971, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 735, in _run_process
    |     async with trio.open_nursery() as nursery:
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 971, in __aexit__
    |     raise combined_error_from_nursery
    | BaseExceptionGroup: Exceptions from Trio nursery (2 sub-exceptions)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 721, in feed_input
      |     await stream.send_all(input)
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_unix_pipes.py", line 136, in send_all
      |     await trio.lowlevel.checkpoint()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 2751, in checkpoint
      |     await _core.wait_task_rescheduled(lambda _: _core.Abort.SUCCEEDED)
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_traps.py", line 178, in wait_task_rescheduled
      |     return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/h/Git/trio/.venv/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
      |     raise captured_error
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 1437, in raise_cancel
      |     raise Cancelled._create()
      | trio.Cancelled: Cancelled
      | 
      | During handling of the above exception, another exception occurred:
      | 
      | Traceback (most recent call last):
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 718, in feed_input
      |     async with stream:
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_abc.py", line 309, in __aexit__
      |     await self.aclose()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_unix_pipes.py", line 199, in aclose
      |     await trio.lowlevel.checkpoint()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 2751, in checkpoint
      |     await _core.wait_task_rescheduled(lambda _: _core.Abort.SUCCEEDED)
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_traps.py", line 178, in wait_task_rescheduled
      |     return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/h/Git/trio/.venv/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
      |     raise captured_error
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 1437, in raise_cancel
      |     raise Cancelled._create()
      | trio.Cancelled: Cancelled
      +---------------- 2 ----------------
      | Traceback (most recent call last):
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 754, in _run_process
      |     await proc.wait()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 243, in wait
      |     async with self._wait_lock:
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_sync.py", line 122, in __aenter__
      |     await self.acquire()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_sync.py", line 589, in acquire
      |     await trio.lowlevel.checkpoint_if_cancelled()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 2773, in checkpoint_if_cancelled
      |     await _core.checkpoint()
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 2751, in checkpoint
      |     await _core.wait_task_rescheduled(lambda _: _core.Abort.SUCCEEDED)
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_traps.py", line 178, in wait_task_rescheduled
      |     return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |   File "/home/h/Git/trio/.venv/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
      |     raise captured_error
      |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_core/_run.py", line 1437, in raise_cancel
      |     raise Cancelled._create()
      | trio.Cancelled: Cancelled
      +------------------------------------
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 779, in _run_process
    |     deliver_cancel_outcome.unwrap()
    |   File "/home/h/Git/trio/.venv/lib/python3.11/site-packages/outcome/_impl.py", line 213, in unwrap
    |     raise captured_error
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/src/trio/_subprocess.py", line 770, in inner_killer
    |     await deliver_cancel(proc)
    |   File "/home/h/Git/trio/capture_run_process_deliver_cancel/foo.py", line 11, in custom_deliver_cancel
    |     raise ValueError("foo")
    | ValueError: foo
    +------------------------------------
```


That's ... not an improvement, at least if we view it as an error that's meant to be read by a human.
The one way I managed to get rid of the excess output is
```python
    try:
        [...]
    finally:
        if isinstance(deliver_cancel_outcome, outcome.Error):
            raise deliver_cancel_outcome.error from None
```
but that seems dangerous. Can add a bunch of logic on top of it so we only suppress `Cancelled`... sounds not fun.


So we probably should just stick with the extra wrapping and document it, and let the nurseries do their thing.

**Comment by richardsheridan** [comment]
> So we probably should just stick with the extra wrapping and document it, and let the nurseries do their thing.

To lead off, I agree with this outcome. I'd just note that although the traceback is inferior, the key difference is that one is wrapped and the other is unwrapped, and this mess might be the best traceback we could produce for the unwrapped case (were that a hard requirement).

**Comment by richardsheridan** [comment]
> ... the key difference is that one is wrapped and the other is unwrapped...

that is, unwrapped at the point where a user might write

```python

try:
    await trio.run_process(...)
except ValueError:
    handle_error()
```

**Comment by CoolCat467** [comment]
I linked this issue to the pull request, didn't really know linking in this case meant closing this issue when that PR was merged, sorry about that

**Comment by jakkdl** [comment]
oh yeah no worries, I noticed it back then but didn't bother changing it. But yeah linking = issue gets automatically closed on PR merge, which certainly isn't super obvious.

**Comment by Zac-HD** [comment]
Only if you use specific keywords though - see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by jakkdl** [comment]
> Only if you use specific keywords though - see https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

well, that's about how mentioning the issue in text might or might not link it depending on leading keyword. I think coolcat467 linked it "manually". But linking always means auto-close, afaict
