### ISSUE TITLE
Gunicorn worker fails to boot due to NotImplementedError 

### ISSUE THREAD

**Issue by codebanesr** [python-trio/trio#2960]
**Description:**
I'm encountering a `NotImplementedError: unsupported platform` which causes my Gunicorn worker process to fail. This seems to be originating from the httpx/trio libraries.  Has anyone else experienced similar issues?  

**Error Traceback:**
```
[2024-02-18 21:08:17 -0800] [42822] [ERROR] Exception in worker process
Traceback (most recent call last):
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
  worker.init_process()
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
  super().init_process()
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
  self.load_wsgi()
 File "/opt/homebrew/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
  self.wsgi = self.app.wsgi()
        ^^^^^^^^^^^^^^^
  ... (Remainder of traceback) 
NotImplementedError: unsupported platform
```

**Environment:**
* **OS:**  Mac M2 [darwin]
* **Python:**  3.11.7
* **Gunicorn:**  version 21.2.0
* **httpx:**  Version (output of `pip show httpx`)
```
Name: httpx
Version: 0.25.0
Summary: The next generation HTTP client.
Home-page: 
Author: 
Author-email: Tom Christie <tom@tomchristie.com>
License: 
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: certifi, httpcore, idna, sniffio
Required-by: anthropic, gotrue, openai, postgrest, qdrant-client, storage3, supabase, supafunc
```

* **trio:** Version (output of `pip show trio`)
```
Name: trio
Version: 0.23.1
Summary: A friendly Python library for async concurrency and I/O
Home-page: https://github.com/python-trio/trio
Author: Nathaniel J. Smith
Author-email: njs@pobox.com
License: MIT OR Apache-2.0
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: attrs, idna, outcome, sniffio, sortedcontainers
Required-by: selenium, trio-websocket
```

Let me know if any more details are necessary.

**Comment by codebanesr** [comment]
The error originates here
<img width="1117" alt="Screenshot 2024-02-18 at 9 19 15 PM" src="https://github.com/python-trio/trio/assets/17947802/67acc37c-b69f-4d44-9694-6fbd8ff8f52d">

**Comment by CoolCat467** [comment]
This sounds incredibly similar to #2848

**Comment by jakkdl** [comment]
> The error originates here, and it only happens when i try to run the app with gunicorn and eventlet <img alt="Screenshot 2024-02-18 at 9 19 15 PM" width="1117" src="https://private-user-images.githubusercontent.com/17947802/305796848-67acc37c-b69f-4d44-9694-6fbd8ff8f52d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzA0ODgsIm5iZiI6MTcwODMzMDE4OCwicGF0aCI6Ii8xNzk0NzgwMi8zMDU3OTY4NDgtNjdhY2MzN2MtYjY5Zi00ZDQ0LTk2OTQtNmZiZDhmZjhmNTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA4MDk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZGFjZmZlOTNmNzBjYTVhYTMxOWQ5ZWZhYjVkYmU0MDI1ODdlMzNlYTAwZTJlMmEwYzg5MDVlMWQzOGVjZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UWD8gt3--lw48meS4xP8JKNX1WjJyoPcThc5SyWhE4g">

right yeah, if we're getting here in the logic then we're neither on windows nor linux (true), and the `select` module does not appear to have `kqueue` (so apparently `gevent.select` does not have `kqueue` either. So indeed similar to #2848, but would not be resolved by #2928.

**Comment by A5rocks** [comment]
Yeah in #2928 I could make things work via `gevent.monkey.get_original` but I don't think that's really the right behavior. That will make `trio.run` block, I think.

Not entirely sure what is the best outcome to have here.

**Comment by A5rocks** [comment]
@codebanesr does this still fail? That PR was merged a while ago but I forgot to check back here.

**Comment by abhra-bv** [comment]
I am using mysql-connector in a flask env . I have gevent for sockets, and the trio still errors out on mac. Im just using mac for development purposes.any way we can get past this in a mac

**Comment by A5rocks** [comment]
> I am using mysql-connector in a flask env . I have gevent for sockets, and the trio still errors out on mac. Im just using mac for development purposes.any way we can get past this in a mac

Sorry I forgot about one extra workaround I should have specified in your issue: httpx, or well really httpcore as of 1.0.6 handles trio raising this error as if trio doesn't exist.

**Comment by A5rocks** [comment]
I'm unable to reproduce this anymore with the following:
```sh
(repro-venv) # /t/tmp.IWl7yl0JXm> cat x.py
def app(environ, start_response):
  import trio
  start_response("200 OK", [])
  return [b"Hello, world!\n"]
(repro-venv) # /t/tmp.IWl7yl0JXm> python -m gunicorn -w 4 x:app &
(repro-venv) # /t/tmp.IWl7yl0JXm> [2025-03-20 23:14:40 +0000] [141363] [INFO] Starting gunicorn 23.0.0
[2025-03-20 23:14:40 +0000] [141363] [INFO] Listening at: http://127.0.0.1:8000 (141363)
[2025-03-20 23:14:40 +0000] [141363] [INFO] Using worker: sync
[2025-03-20 23:14:40 +0000] [141364] [INFO] Booting worker with pid: 141364
[2025-03-20 23:14:40 +0000] [141365] [INFO] Booting worker with pid: 141365
[2025-03-20 23:14:41 +0000] [141366] [INFO] Booting worker with pid: 141366
[2025-03-20 23:14:41 +0000] [141367] [INFO] Booting worker with pid: 141367
                                               curl http://127.0.0.1:8000
Hello, world!
(repro-venv) # /t/tmp.IWl7yl0JXm> fg
Send job 1 (python -m gunicorn -w 4 x:app &) to foreground
^C[2025-03-20 23:14:52 +0000] [141363] [INFO] Handling signal: int
[2025-03-20 23:14:53 +0000] [141365] [INFO] Worker exiting (pid: 141365)
[2025-03-20 23:14:53 +0000] [141367] [INFO] Worker exiting (pid: 141367)
[2025-03-20 23:14:53 +0000] [141364] [INFO] Worker exiting (pid: 141364)
[2025-03-20 23:14:53 +0000] [141366] [INFO] Worker exiting (pid: 141366)
[2025-03-20 23:14:53 +0000] [141363] [INFO] Shutting down: Master
```

I think we must have fixed this issue a few versions ago.
