### ISSUE TITLE
v0.25.0 Broke support for Windows embedded Python

### ISSUE THREAD

**Issue by richard-lancaster-sp** [python-trio/trio#2987]
```
c:\python-3.11.5-embed-amd64>python.exe -c "import trio; print(trio.__version__)"
0.24.0

c:\python-3.11.5-embed-amd64>python -m pip install trio==v0.25.0
Collecting trio==v0.25.0
... 
Successfully installed trio-0.25.0

c:\python-3.11.5-embed-amd64>python.exe -c "import trio; print(trio.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python-3.11.5-embed-amd64\Lib\site-packages\trio\__init__.py", line 76, in <module>
    from ._path import Path as Path, PosixPath as PosixPath, WindowsPath as WindowsPath
  File "c:\python-3.11.5-embed-amd64\Lib\site-packages\trio\_path.py", line 99, in <module>
    class Path(pathlib.PurePath):
  File "c:\python-3.11.5-embed-amd64\Lib\site-packages\trio\_path.py", line 116, in Path
    @_wraps_async(pathlib.Path.cwd)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\python-3.11.5-embed-amd64\Lib\site-packages\trio\_path.py", line 41, in decorator
    assert wrapped.__doc__ is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

c:\python-3.11.5-embed-amd64>
```

We're using trio and Windows embedded python (https://www.python.org/downloads/windows/), v0.25.0 broke support for this version of python as it assumes the inclusion of __doc__ strings.

**Comment by jakkdl** [comment]
Fixed by #2979
