### ISSUE TITLE
Regression: unix socket bind does not work with a PathLike argument

### ISSUE THREAD

**Issue by regnarg** [python-trio/trio#3041]
trio.socket.SocketType.bind no longer works with a PathLike (e.g. pathlib.Path) argument.

Simple test program:
```python
import socket, trio.socket
from pathlib import Path

async def main():
    sock = trio.socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    await sock.bind(Path('/tmp/x.sock'))

trio.run(main)
```

Results in:
```
Traceback (most recent call last):
  File "/tmp/x.py", line 8, in <module>
    trio.run(main)
  File "/usr/lib/python3.12/site-packages/trio/_core/_run.py", line 2305, in run
    raise runner.main_task_outcome.error
  File "/tmp/x.py", line 6, in main
    await sock.bind(Path('/tmp/x.sock'))
  File "/usr/lib/python3.12/site-packages/trio/_socket.py", line 874, in bind
    address = await self._resolve_address_nocp(address, local=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/trio/_socket.py", line 922, in _resolve_address_nocp
    return await _resolve_address_nocp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/trio/_socket.py", line 472, in _resolve_address_nocp
    assert isinstance(address, (str, bytes))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

This bugs seems to have been introduced in [cf1f3c745](https://github.com/python-trio/trio/commit/cf1f3c745#diff-300b958089de6b62596dad8182b7dfb234ac01d922fdbce3456f641c5a9964e1R466), released in v0.23.0.

**Comment by CoolCat467** [comment]
You can fix this by doing this:
```python
import socket, trio.socket
from pathlib import Path

async def main():
    sock = trio.socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    await sock.bind(str(Path('/tmp/x.sock')))

trio.run(main)
```

**Comment by regnarg** [comment]
> You can fix this by doing this:

I am of course aware of that. But still: (1) it broke my existing code,
(2) it makes for a much less nice API when the caller has to think of
this, (3) the code was clearly meant to accept Path objects, as the
surrounding comments and the call to os.fspath suggest.

**Comment by jakkdl** [comment]
I don't think this passed, or passes, typing? The method is typed as

```python
Address: TypeAlias = Union[
    str, bytes, Tuple[str, int], Tuple[str, int, int], Tuple[str, int, int, int]
]
async def bind(self, address: Address) -> None:
  ...
```

and was previously
```python
async def bind(self, address: tuple[object, ...] | str | bytes) -> None:
```

But yeah you're totally right that the comment mentions "path-likes", and as such the typing should be updated to include `Path` and/or `PathLike` and the assertion changed. Thank you!
