### ISSUE TITLE
nursery replaces custom ExceptionGroup subclasses with plain ExceptionGroups

### ISSUE THREAD

**Issue by graingert** [python-trio/trio#3175]
```python
import trio

class MyExceptionGroup(ExceptionGroup):
    pass


async def main():
    async with trio.open_nursery():
        raise MyExceptionGroup("hello", [ValueError("bad")])

trio.run(main)
```

output:
```pytb
  + Exception Group Traceback (most recent call last):
  |   File "/home/graingert/projects/demo.py", line 11, in <module>
  |     trio.run(main)
  |   File "/home/graingert/.virtualenvs/anyio_fixture_methods/lib/python3.12/site-packages/trio/_core/_run.py", line 2306, in run
  |     raise runner.main_task_outcome.error
  |   File "/home/graingert/projects/demo.py", line 8, in main
  |     async with trio.open_nursery():
  |   File "/home/graingert/.virtualenvs/anyio_fixture_methods/lib/python3.12/site-packages/trio/_core/_run.py", line 959, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/graingert/projects/demo.py", line 9, in main
    |     raise MyExceptionGroup("hello", [ValueError("bad")])
    | ExceptionGroup: hello (1 sub-exception)
    +-+---------------- 1 ----------------
      | ValueError: bad
      +------------------------------------
```

expected output:

```pytb
  + Exception Group Traceback (most recent call last):
  |   File "/home/graingert/projects/demo.py", line 11, in <module>
  |     trio.run(main)
  |   File "/home/graingert/.virtualenvs/anyio_fixture_methods/lib/python3.12/site-packages/trio/_core/_run.py", line 2306, in run
  |     raise runner.main_task_outcome.error
  |   File "/home/graingert/projects/demo.py", line 8, in main
  |     async with trio.open_nursery():
  |   File "/home/graingert/.virtualenvs/anyio_fixture_methods/lib/python3.12/site-packages/trio/_core/_run.py", line 959, in __aexit__
  |     raise combined_error_from_nursery
  | ExceptionGroup: Exceptions from Trio nursery (1 sub-exception)
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/home/graingert/projects/demo.py", line 9, in main
    |     raise MyExceptionGroup("hello", [ValueError("bad")])
    | MyExceptionGroup: hello (1 sub-exception)
    +-+---------------- 1 ----------------
      | ValueError: bad
      +------------------------------------
```

**Comment by graingert** [comment]
The problem is that splitting Cancelled from an ExceptionGroup tree converts custom EG subclasses into regular EGs:

https://github.com/python-trio/trio/blob/3de7996cb82baa991f0689f854ef3791fffcd177/src/trio/_core/_run.py#L641-L648

**Comment by A5rocks** [comment]
Do we need to provide our own `.split`?

```pycon
>>> class ExampleEG(ExceptionGroup):
...     pass
...
>>> eg = ExampleEG("test", [ValueError("bad")])
>>> eg.split(TypeError)
(None, ExceptionGroup('test', [ValueError('bad')]))
>>> eg.split(ValueError)
(ExceptionGroup('test', [ValueError('bad')]), None)
>>> eg
ExampleEG('test', [ValueError('bad')])
```

Also, is this something we should report upstream to CPython?

**Comment by graingert** [comment]
I think the fix is using a custom split that doesn't recreate ExceptionGroups if the children aren't changing.

Probably it is worth reporting

**Comment by TeamSpen210** [comment]
For custom subclasses, you need to define [derive()](https://docs.python.org/3/library/exceptions.html#BaseExceptionGroup.derive), so it knows how to create instances - it's not safe obviously to assume the constructor args are the same.

**Comment by A5rocks** [comment]
Should we warn about that and provide a sane alternative?

**Comment by jakkdl** [comment]
defining an `ExceptionGroup` subclass without a `derive` could maybe be a linter warning? (either flake8-async or flake8-bugbear)
I don't think trio should create a custom `split` here

**Comment by Zac-HD** [comment]
Closing this issue because the solution is to define ` MyExceptionGroup.derive()`, and we've also opened an issue for `flake8-async` to warn if you forgot to do so.
