### ISSUE TITLE
"Native" async generator-based context managers do not get KI protected

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio#445]
This test code fails both `currently_ki_protected` assertions.

```
import trio
from async_generator import asynccontextmanager

@trio.hazmat.enable_ki_protection
@asynccontextmanager
async def bar():
	assert trio.hazmat.currently_ki_protected()
	yield 1234
	assert trio.hazmat.currently_ki_protected()
	
async def foo():
	async with bar() as num:
		assert num == 1234
trio.run(foo)
```

**Comment by SunDwarf** [comment]
This also happens with 3.7 contextlib asynccontextmanager, for posterity.

**Comment by njsmith** [comment]
What if you swap the order of the two decorators?

**Comment by smurfix** [comment]
You can't swap them.
```
Traceback (most recent call last):
  File "/tmp/t.py", line 5, in <module>
    @trio.hazmat.enable_ki_protection
  File "/usr/lib/python3/dist-packages/async_generator/_util.py", line 100, in asynccontextmanager
    "must be an async generator (native or from async_generator; "
TypeError: must be an async generator (native or from async_generator; if using @async_generator then @acontextmanager must be on top.
```

**Comment by SunDwarf** [comment]
You can with 3.7's asynccontextmanager, and it works 100% fine with swapped decorators. So this might be an incompatibility with async_generator?

**Comment by njsmith** [comment]
Yeah, I guess we can disable that check in `@asynccontextmanager`. I think I was just nervous about people accidentally putting `@async_generator` on top of `@asynccontextmanager`, which doesn't make any sense but in a sort of confusing way. We could probably catch that in another way though, like by having `@async_generator` give a special error message if it sees a `_AsyncGeneratorContextManager` object instead of a coroutine.

Alternatively, maybe we should make `@ki_protected_(async)contextmanager` decorators, which would also ensure that the `__(a)exit__` is decorated appropriately to reduce a small race condition? It isn't terribly useful until Python bug [bpo-29988](https://bugs.python.org/issue29988) is fixed, but hopefully that will happen eventually...
