### ISSUE TITLE
Support Pythonista (iOS python environment)

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#684]
@mikaelho reports in https://github.com/python-trio/trio/issues/673#issuecomment-424958895 that on [Pythonista](http://omz-software.com/pythonista/), `signal.getsignal(signal.SIGINT)` has been hacked somehow to return `None`. But `trio._util.is_main_thread` assumes that the return value from `getsignal` is a valid input to `signal`; specifically it does:

```python
signal.signal(signal.SIGINT, signal.getsignal(signal.SIGINT))
```

But when `getsignal` returns `None`, this doesn't work, so `is_main_thread` crashes, and this makes trio unusable in Pythonista.

I'm not really sure how Pythonista works or what the right thing to do here is... in regular Python, `getsignal` cannot return None, so I guess we can detect when we're on Pythonista, but then what? Does iOS even have signals? Does Pythonista have any way to do control-C?

A simple hack would be to add a check for `getsignal` returning None, and if it does then return `False` from `is_main_thread` – this would effectively disable signal handling on Pythonista, which seems like plausibly the right thing to do?

We might need to rewrite `is_main_thread` entirely anyway, to fix #673.

@mikaelho While we're at it, what does this return on Pythonista?

```python
signal.signal(signal.SIGINT, signal.SIG_DFL)
```

?

**Comment by mikaelho** [comment]
>>> str(signal.signal(signal.SIGINT, signal.SIG_DFL))
    'Handlers.SIG_DFL'

**Comment by mikaelho** [comment]
I tried this. Now running the script just returns, printing nothing.

    import trio, signal
    
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    
    async def async_double(x):
        return 2 * x
    
    trio.run(async_double, 3)  # returns 6

**Comment by mikaelho** [comment]
Tried this script:

    import trio, signal
    
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    
    async def test_func():
      await trio.sleep(15)
    
    trio.run(test_func)
    
Pythonista did not react to the normal Ctrl-C equivalent ('X' in the user interface), but blurted out this exception at 15 seconds:

    Traceback (most recent call last):
      File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 1314, in run
        run_impl(runner, async_fn, args)
      File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 1378, in run_impl
        runner.io_manager.handle_io(timeout)
      File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_io_kqueue.py", line 48, in handle_io
        batch = self._kqueue.control([], max_events, timeout)
    KeyboardInterrupt
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/Testailut/triobasic.py", line 8, in <module>
        trio.run(test_func)
      File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 1320, in run
        ) from exc
    trio.TrioInternalError: internal error in trio - please file a bug!
    
I know this now veering off towards the "weird iOS app" country, but I would be sure grateful for even a rough workaround. I will try to find more what that 'X' does exactly - at least it delivers a KeyboardInterrupt.

**Comment by njsmith** [comment]
So there are a few strange things that jump out at me here:

* `signals.getsignal` reports that the current handler is `None`, which isn't a meaningful return value
* If we use `signal.signal` to change the current handler, it returns the old value. Here, it says that the old value was `SIG_DFL`, which contradicts what `getsignal` says.
* Also, since `signal.signal(SIGINT, SIG_DFL)` reports that `SIG_DFL` was already the handler, it's claiming that we didn't do anything. It's as if we set `x = x`. Yet calling this does apparently change how scripts behave. (I guess probably what it does is make `getsignal` start returning `SIG_DFL` instead of `None`?)

That's all annoying, but should be work-aroundable to at least make it so trio programs don't automatically crash. It might even happen automatically from fixing #673.

Making the X button work, though, looks more difficult. From your description, my guess is that it doesn't send a signal at all, but instead uses this other mechanism that the python interpreter has, where you can request another thread to run some function whenever it gets a chance. I think it's called `Py_AddPendingCall`.

There are two problems with this. First, it just adds the function to an internal queue, that the interpreter checks manually from time to time. But if the interpreter is sleeping, then it's not checking this queue. That's why you have to wait 15 seconds for the `KeyboardInterrupt` to arrive. I guess a simple `time.sleep` has the same problem? Signals OTOH have several mechanisms to trigger the target thread to wake up and notice them, but if it's not using signals then these don't work.

And second, if that's what the X does, then there's no way for trio to intercept it and handle it more appropriately, the way it can with regular signals. In particular, it can't protect it's delicate internals from getting `KeyboardInterrupt` at places where it can't be handled gracefully.

That means there's not much that can be done about this from Trio's side – slow delivery and `TrioInternalError`s seem inevitable :-(.

Is pythonista maintained? Is the dev accessible? I'd be happy to talk to them about what they need to do to solve this part.

**Comment by mikaelho** [comment]
Short answer to dev accessibility topic is that "probably not in the short term". Pythonista is a pretty significant piece of software, with a full IDE, graphical UI designer, custom libraries bridging python and native iOS features like UI, speech recognition, etc., and lately the dev has been unresponsive. If that changes, I expect him to have quite a lot of more pressing issues on his plate. Just in case, I have updated an old issue in Pythonista issue tracker, and might create a new one later.

Meanwhile, I am trying to work around this issue to get experimenting with trio on my phone. I can catch the internal error for now, but the next run will then have issues (see below). Is there any way for me to clean up manually in case of this specific error?

```
Exception ignored in: <bound method Nursery.__del__ of <trio._core._run.Nursery object at 0x112e20160>> Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 521, in __del__
    assert not self._children
AssertionError: 
Exception ignored in: <coroutine object Scripter._runner at 0x11238f780> Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/Git/scripter/trio-scripter.py", line 158, in _runner
    await scr.wake_up.wait()
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_ki.py", line 162, in wrapper
    return fn(*args, **kwargs)
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 248, in __exit__
    remaining_error_after_cancel_scope = self._scope._close(exc)
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 225, in _close
    self._remove_task(self._scope_task)
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 200, in _remove_task
    self._tasks.remove(task)
  File "/var/containers/Bundle/Application/29748688-5C34-4B85-A54D-9874F692C45A/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/contextlib.py", line 90, in __exit__
    next(self.gen)
  File "/private/var/mobile/Containers/Shared/AppGroup/DB278AED-4773-408E-8500-E06A4DF50B70/Pythonista3/Documents/site-packages-3/trio/_core/_run.py", line 152, in _might_change_effective_deadline
    runner = GLOBAL_RUN_CONTEXT.runner
AttributeError: '_thread._local' object has no attribute 'runner'
```

**Comment by mikaelho** [comment]
Thank you.

For now, I will experiment with using `gc.collect()` and some very specific warning filters, and refrain from reporting any "bugs" unless I can replicate them on other platforms.

**Comment by mikaelho** [comment]
@njsmith, as you led me to expect, `gc.collect()` issued at closing moved the ”Exception ignored” error from the start of the next run to the closing of this run. This is more sane and tractable.

Is there a good way to silence the notification from the Nursery object at that point? I have looked at the docs and did not find anything there; standard warning filtering does not seem to apply.

**Comment by njsmith** [comment]
> Is there a good way to silence the notification from the Nursery object at that point? I have looked at the docs and did not find anything there; standard warning filtering does not seem to apply.

It looks like when there's an unhandled exception in `__del__`, Python simply prints it directly to `sys.stderr`:

https://github.com/python/cpython/blob/077061a7b24917aaf31057885c69919c5a553c88/Python/errors.c#L946-L1028

So I guess the only way to capture it would be to temporarily replace `sys.stderr` :-/.

BTW, a gross little hack that occurred to me: if you want to make trio notice more quickly when you've hit the X button, you could set `trio._core._run._MAX_TIMEOUT` to some small value. E.g. if you set it to `0.5`, then trio will wake up every 0.5 seconds, and notice any injected `KeyboardInterrupt`.

(Tiny warning that you can probably ignore completely: if you use [wait_all_tasks_blocked](https://trio.readthedocs.io/en/latest/reference-testing.html#trio.testing.wait_all_tasks_blocked) with a non-zero timeout, then make sure the value you set `_MAX_TIMEOUT` to is *larger* than the longest timeout you'll ever pass to `wait_all_tasks_blocked`.)

**Comment by mikaelho** [comment]
Thank you. So with the code below we see no evil, hear no evil:

      try:
        trio.run(scr._runner)
      except trio.TrioInternalError:
        with contextlib.redirect_stderr(os.devnull):
          gc.collect()

**Comment by mikaelho** [comment]
After adding a nursery I started getting even more intractable errors, so decided that another approach is needed. I now run an small overlay view in Pythonista's UI thread. This view has a custom 'X' which closes the overlay view and cancels the topmost nursery, ending the trio.run cleanly. I will create a UI application template as well, for full UI applications that want to take advantage of trio in the background.

Is introducing a top-level nursery just for the purposes of a cancel scope the best option for this, or is there a higher-level cancel scope that I could use?
