### ISSUE TITLE
"OSError: [Errno 22] Invalid argument" was  encountered when saving files in windows

### ISSUE THREAD

**Issue by HeLiangHIT** [python-trio/trio#815]
+ The code I used is as follows:
```
    async def save_file(self, name, content):
        file_path = os.path.join(self.save_dir, fname_normalize(name))
        fd = await trio.open_file(file_path, 'wb')
        await fd.write(content)
        await fd.aclose()
```
+ The error stack information:
```
Traceback (most recent call last):
File "douyin_downloader\douyin_downloader.py", line 116, in 
File "douyin_downloader\douyin_downloader.py", line 111, in cmd_run
File "site-packages\trio_core_run.py", line 1337, in run
File "douyin_downloader\douyin_downloader.py", line 95, in main
File "douyin_downloader\douyin_downloader.py", line 66, in crawler_user_video
File "site-packages\trio_core_run.py", line 397, in aexit
File "douyin_downloader\douyin_downloader.py", line 43, in download_videos
File "douyin_downloader\util.py", line 237, in save_file
File "site-packages\trio_file_io.py", line 170, in open_file
File "site-packages\trio_threads.py", line 400, in run_sync_in_worker_thread
File "site-packages\trio_core_traps.py", line 165, in wait_task_rescheduled
File "site-packages\outcome_sync.py", line 111, in unwrap
File "site-packages\trio_threads.py", line 362, in do_release_then_return_res
ult
File "site-packages\outcome_sync.py", line 111, in unwrap
OSError: [Errno 22] Invalid argument: 'F:\Tik Tok\97553783068\favorite\"阿敏
啊_62044195126_我能.mp4'
[1732] Failed to execute script douyin_downloader
```
+ the related version is trio==0.9.0

I guess this error is related to the file name, but why?

**Comment by njsmith** [comment]
Oh ugh yeah that's frustrating, but at least it makes sense... Thanks for the update!
