### ISSUE TITLE
Can we make abort functions more composable?

### ISSUE THREAD

**Issue by oremanj** [python-trio/trio#896]
In chat today, [@njsmith gave](https://gitter.im/python-trio/general?at=5c520ee941775971a0ad9a91) a neat example of how to build a resource-aware job scheduler using `trio.Event`. He mentioned that doing the bookkeeping in the task that's doing the wakeup, rather than in the task that's being woken up, seems broadly essential to avoiding race conditions (which I agree with).

I think there's a rough edge with respect to how cancellation handling fits into this, though:
* If you block with `wait_task_rescheduled`, your `abort_fn` runs synchronously with the cancellation being delivered. So if the waking task sees that you're still registered, you won't be cancelled before you're woken up; and if you do get cancelled, the waking task won't see you as still eligible to be woken up. This is great. It means the most natural way to handle cancellation is also relatively race-proof.
* But if you block by calling some other abstraction, such as `trio.Event.wait()`, the only way you can do cleanup on cancellation is by catching the `Cancelled` exception after it's injected. Moreover, it's possible that a task gets cancelled, but that before it next runs to deliver the cancellation, it also is woken up due to the resource it was waiting for becoming available. Now we're back to writing bookkeeping logic inside the woken task. This is less great.

It seems to me that we might be well served by having a way of effectively composing abort functions. That is, when I say `await event.wait()`, I should have the option of designating some code that will run _synchronously_ with a cancellation of `event.wait()`.

Doing this in a way that lets the outer logic block the cancellation (i.e., exposing the full `abort_fn` power) is very tricky. Doing it in a way that only supports supplying additional code to run when the cancellation succeeds is probably easier though. Do folks have thoughts on whether this is desirable, independent of how it might best be implemented?

**Comment by ktarplee** [comment]
A almost cycling example of the above gist is [here](https://gist.github.com/ktarplee/f9fb7c2a06d960f5c31cbcbf2b5c4131).

I was able to fix all the minor errors in the code and try to cycle it but it still fails catastrophically with an internal trio error.

```
task 3 started with cpu_count=15, gpu_count=2
task 3 running
task 9 started with cpu_count=38, gpu_count=0
task 4 started with cpu_count=22, gpu_count=2
task 7 started with cpu_count=20, gpu_count=2
task 2 started with cpu_count=14, gpu_count=1
task 1 started with cpu_count=32, gpu_count=0
task 0 started with cpu_count=21, gpu_count=1
task 6 started with cpu_count=1, gpu_count=2
task 8 started with cpu_count=22, gpu_count=0
task 8 running
task 5 started with cpu_count=11, gpu_count=1
task 3 finished
task 2 running
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/trio/_core/_run.py", line 1323, in run
    run_impl(runner, async_fn, args)
  File "/usr/local/lib/python3.7/site-packages/trio/_core/_run.py", line 1471, in run_impl
    runner.task_exited(task, final_outcome)
  File "/usr/local/lib/python3.7/site-packages/trio/_core/_run.py", line 944, in task_exited
    self.tasks.remove(task)
KeyError: <Task '__main__.worker' at 0x10ff8bc18>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aux/trio_resource_pool.py", line 100, in <module>
    trio.run(main)
  File "/usr/local/lib/python3.7/site-packages/trio/_core/_run.py", line 1329, in run
    ) from exc
trio.TrioInternalError: internal error in trio - please file a bug!
Exception ignored in: <function Nursery.__del__ at 0x10fd5d510>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/trio/_core/_run.py", line 530, in __del__
AssertionError: 
```

**Comment by ktarplee** [comment]
The approach of using trio.Event instead of trio.hazmat.Task for the key of self._waiters works fine (but probably does not have the desired cancelling behavior that you guys want).

**Comment by ktarplee** [comment]
I have a working trio.Event based implementation of this same idea and that is what I had to do however I deleted the waiter after the `await` statement so I was not modifying the dict that we are iterating over.  I tried that with the `wait_task_rescheduled` impl and had no luck.

Do I need to collect all tasks to reschedule, then delete them from waiters, then reschedule each?

**Comment by ktarplee** [comment]
Something like...
```python
awake = []
for other_task, other_wanted in self._waiters.items():
    if other_wanted in self._available:
        self._available -= other_wanted
        awake.append(other_task)

for other_task in awake:
    del self._waiters[other_task]
    
for other_task in awake:
    trio.hazmat.reschedule(other_task)
```

**Comment by njsmith** [comment]
@ktarplee The lazy solution is:

```python
            for other_task, other_wanted in list(self._waiters.items()):
                if other_wanted in self._available:
                    self._available -= other_wanted
                    del self._waiters[other_task]
                    trio.hazmat.reschedule(other_task)
```

(Notice the added `list()` call, so that we're iterating over a copy of the dictionary items, instead of the dict itself.) Otherwise, if you want to be less lazy, your solution works too :-) (I'd probably merge the `reschedule` call into one of the other `for` loops.)

> I have a working `trio.Event` based implementation of this same idea

So here's the problem with using `trio.Event`: suppose that someone does something like:

```python
with trio.move_on_after(10):  # I'm only willing to wait 10 seconds for this
    async with resource_pool.claim(...):
        ...
```

And further suppose that the timeout expires while `claim` is waiting to acquire the resources, so it's blocked in `event.wait()`. When this happens, the `event.wait()` call raises `trio.Cancelled`, and we unwind out of the call to `claim`. And when we do... we leave behind the entry in `resource_pool._waiters` claiming that we're waiting for those resources, even though we aren't anymore. Later on, some other task will notice us waiting, and hand us those resources, excepting us to hand them back later when we're done. But we're already gone, so we'll never hand back the resources, so they'll just leak. It's a pretty serious correctness bug.

(You might think: well, maybe I can catch that `Cancelled` exception and remove the entry from the `resource_pool._waiters`. But this is complicated, because it could happen that someone handed us the resources in *between* when trio decided to send the `Cancelled` exception, and when the task was resumed and received the exception... in the `wait_task_rescheduled` version, this doesn't happen, because the `abort_fn` is run immediately when trio decides that it wants to send `Cancelled`, without waiting for the task to be resumed.)

**Comment by oremanj** [comment]
If I try to concretize my original idea here, I get something like:
```
def fn():
    <bar>
with trio.hazmat.unpublish_using(fn):
    <foo>
```
is equivalent to
```
try:
    <foo>
finally:
    <bar>
```
except that if <foo> is cancelled, <bar> runs immediately when the cancellation occurs, without waiting for the cancelled task to actually be scheduled.

If people think this is a good idea, I don't think it would be difficult to implement, but it sounds like we may want to do something with broader scope instead.
